@baseUrl=http://localhost:3000
@userId=6ab68e1e26dd79acfc2056aa

### create user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "djshah",
  "email": "dj1234@example.com",
  "password": "user@user"
}

### get all users
GET {{baseUrl}}/users

### get user by id
GET {{baseUrl}}/users/{{userId}}

### update user by id
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "John Doe Updated",
  "email": "john.doe.updated@example.com"
}

### delete user by id
DELETE {{baseUrl}}/users/{{userId}}